### PR TITLE
Removed attr and attrs dependency from main version

### PR DESCRIPTION
**Pull request by Fearkin**
What does this implement/fix? Explain your changes.
---------------------------------------------------
Solves this problem (https://github.com/gnebbia/kb/projects/4) via dataclasses from standard library instead of attr. Now only pytest from requirements-dev depends on attrs and attr.

Does this close any currently open issues?
------------------------------------------
Prevents this (https://github.com/gnebbia/kb/issues/76) type of issues

Any relevant logs, error output, etc?
-------------------------------------
I've ran into same issue that I mentioned above (and I had same error) and this fix worked for me

Any other comments?
-------------------
I've also autoformatted many files

Where has this been tested?
---------------------------
All tests passed
**Operating System:** Manjaro 21.0 Ornara (Linux 5.9.16-1-MANJARO)

**Platform:** Python 3.9.2, kb 0.1.6

### CODE REVIEW

**Comment by gnebbia** [comment]
Dear Sir, thanks for the suggestion, but is this compatible with all pythons from 3.6?

**Comment by Fearkin** [comment]
> Dear Sir, thanks for the suggestion, but is this compatible with all pythons from 3.6?

As far as I know, data classes were introduced in version 3.7, so they will not work in versions below this one  :(

**Comment by gnebbia** [comment]
That may be a problem, since the minimum version supported is python 3.6, what do you suggest?

**Comment by Fearkin** [comment]
> That may be a problem, since the minimum version supported is python 3.6, what do you suggest?

What if I try to port dataclasses for version 3.6 via (https://pypi.org/project/dataclasses/) and some version check?

**Comment by gnebbia** [comment]
Correct me if I am wrong, but at this point the dependency would be dataclass instead of attr, I mean we still would have one.

**Comment by Fearkin** [comment]
> Correct me if I am wrong, but at this point the dependency would be dataclass instead of attr, I mean we still would have one.

I meant version check on setup too, so we can install this specific package only for 3.6

**Comment by gnebbia** [comment]
Yes if there such thing we may try, although I also have to deal with PKGBUILDs for arch, and should check out how to specify that

**Pull request closed without merging**
