### PR TITLE
fix: #12

### PR DESCRIPTION
**Pull request by yihong0618**
What does this implement/fix? Explain your changes.
---------------------------------------------------
fix: #12

Does this close any currently open issues?
------------------------------------------
Yes

### CODE REVIEW

**Comment by gnebbia** [comment]
Ok thanks a lot! I merged your PR, and also converted all paths to string in the config.py module.

**Comment by yihong0618** [comment]
> Ok thanks a lot! I merged your PR, and also converted all paths to string in the config.py module.

@gnebbia  please don't 

I have test.

If you str dir file.
when you kb erase then will cause the str can not mkdir problem. 
You can test.

**Comment by yihong0618** [comment]
@gnebbia 

forget it, I see your commit, you passed the Path file~

**Comment by gnebbia** [comment]
Sorry what should I test? in kb erase, no directory is created with mkdir... can you be more specific ?

**Comment by yihong0618** [comment]
@gnebbia 
If you covert all to str, you will find this problem 

image

**Comment by yihong0618** [comment]
image

Maybe only covert these two red square?

**Comment by gnebbia** [comment]
Ok thanks a lot for your help! I think the last commit solved everything, by converting the str back to path when directory creation is required. 
Can you confirm that?
Please do a pip uninstall kb and then a  pip install . # there is a dot
within the kb directory after having pulled the last commits.

**Comment by yihong0618** [comment]
@gnebbia Cool, I think works perfectly.

P.S. 
Thank you for your wonderful repo, that's what I am looking for quite a long time.

**Comment by gnebbia** [comment]
Well thanks to you @yihong0618 ! If you didn't warn me about this, I never would have found the bug!

Thanks for your support and appreciation!
P.S.: Feel free to fork the project or implement new features as pull requests!

**Pull request merged**
