### PR TITLE
Rationalise function "open_non_text_file"

### PR DESCRIPTION
**Pull request by alshapton**
Two versions of the functions existed - one in opener.py, one in utils.py. Seemed like a good idea to remove opener.py and rationalise into utils.py, since it seemed like the open_non_text_file function is a utility function, and having it in a  single python file made for extra needless complexity

What does this implement/fix? Explain your changes.
---------------------------------------------------
Reduces  complexity and number of python files

Does this close any currently open issues?
------------------------------------------
No

Any relevant logs, error output, etc?
-------------------------------------
None

Any other comments?
-------------------
This is a speculative PR based on my thoughts only - happy to have it rejected if it does not fit with the direction of the project.

Where has this been tested?
---------------------------
Locally:
**Operating System:** 
MacOS Catalina 10.15.6

**Platform:** 
MacOS
Python 3.8.5

**Travis:**
[Build 186431760](https://travis-ci.com/github/alshapton/kb/builds/186431760)

### CODE REVIEW

**Comment by gnebbia** [comment]
You are definitely right! The problem is quite simple, I forgot to remove the utils.py.

Indeed, I tend to see utils.py as a sort of anti-pattern, while I prefer to put everything at its own place.
Since I am not using utils.py anywhere but it was just a placeholder for functions at the end I never used.
I think we can definitely remove it!
 
So I will definitely take into account this PR, but just discard utils.py instead of using it!

Sounds fine?

**Comment by alshapton** [comment]
MMMM - I took it the  other way round - I discarded opener.py instead ! -
I'll refactor to remove utils.py if you like !
Let me know !

**Comment by gnebbia** [comment]
I already included your idea in the project! Try to update, you can also update with pip if you prefer!

**Comment by gnebbia** [comment]
Anyway thanks for the improvement!

**Pull request closed without merging**
