### PR TITLE
PKGBUILD dependencies

### PR DESCRIPTION
**Pull request by ArchWizard56**
What does this implement/fix? Explain your changes.
---------------------------------------------------
After installing the package from the Arch User Repository, as described in the README, the program threw an error about requiring two additional packages to be installed. This pull request adds those two dependencies to the PKGBUILDs. I also updated the sha256sum in the PKGBUILD, so that it matched the hash of the version it pulls from github.

EDIT:
I also reviewed the requirements.txt and added a few more dependencies that are probably required, but I already had installed on my system. 

Any relevant logs, error output, etc?
-------------------------------------
The two tracebacks I got, and the solutions that fixed them
https://ghostbin.co/paste/pgjq9j

Where has this been tested?
---------------------------

**Operating System:*Arch Linux* ...

### CODE REVIEW

**Comment by gnebbia** [comment]
Thanks for your fix Sir, but I have doubts about the sha256sum edit, actually, that sha256sum is referred to the archive present on pythonhosted (for the stable version) so it is not the same as the v0.1.6 version on github.

**Comment by gnebbia** [comment]
Also did you try to compile using these PKGBUILDs? I am having errors complainin about the fact that pacman cannot find python-colored, maybe because it is in the AUR?

**Comment by ArchWizard56** [comment]
> Thanks for your fix Sir, but I have doubts about the sha256sum edit, actually, that sha256sum is referred to the archive present on pythonhosted (for the stable version) so it is not the same as the v0.1.6 version on github.

Yeah, I needed to change the sha256sum in order to get the package to build because the stable version pulls from pythonhosted instead of GitHub. If we want to pull from GitHub, then we should probably change the source.

> Also did you try to compile using these PKGBUILDs? I am having errors complainin about the fact that pacman cannot find python-colored, maybe because it is in the AUR?

Yes, python-colored is in the AUR, according to this [post](https://github.com/Jguer/yay/issues/934), in order to test the PKGBUILDS, something like `yay -S --asdeps python-colored` can be run, and that works for me. Once the PKGBUILDS are uploaded to the AUR, however, yay, or whatever AUR helper, should automatically resolve them and install the required AUR package.

**Comment by gnebbia** [comment]
Ok thanks a lot Sir, merged!

**Comment by ArchWizard56** [comment]
Thank you, sir, for this amazing project! I'm glad I could be helpful!

**Comment by gnebbia** [comment]
Thanks  a lot to you for having contributed!You were very helpful!

**Pull request closed without merging**
