### PR TITLE
Create Aliases on Windows

### PR DESCRIPTION
**Pull request by UweZiegenhagen**
What does this implement/fix? Explain your changes.
---------------------------------------------------
Added comments on how to add aliases in Windows

Does this close any currently open issues?
------------------------------------------
no

Any relevant logs, error output, etc?
-------------------------------------
(If it’s long, please paste to https://ghostbin.com/ or https://bpaste.net and insert the link here.)

no

Any other comments?
-------------------

nice tool, great work

Where has this been tested?
---------------------------

**Operating System:** Windows 10 PRO

**Platform:** ...

**Target Platform:** ...

### CODE REVIEW

**Comment by alshapton** [comment]
@UweZiegenhagen This is a great bit of work for those in the Windows community. I think that it may be better to have the aliases for various flavours of *nix / MacOS / Windows etc in a folder where people can take the one they want and add it to their profile/startup script etc. The aliases listed in the README now and yours could form the basis of that - with corresponding instructions in the README pointing people to those files.
Thoughts ?

**Comment by UweZiegenhagen** [comment]
Good idea. However I only started using kb so I'm a newbie. My proposal is to leave it in README.MD for the moment. I see if I can invest some time to move it into another document in the next days.

**Comment by alshapton** [comment]
That's OK, Uwe - thank you for your contribution and welcome to the world
of kb !!!

**Comment by alshapton** [comment]
@UweZiegenhagen Do you want this PR to be accepted now, or will you work on putting it in a couple of files over the next days, and then we'll accept the PR (or we can do it now)

**Comment by UweZiegenhagen** [comment]
@alshapton Please accept now, I'll be pretty busy the next days.

**Comment by gnebbia** [comment]
Ok, sorry for the delay in merging this, anyway I added additional documentation to allow user to perform all the steps by command line.
Let me know what do you think.
I detailed the insertion of the aliases both for cmd.exe and powershell and I also added how to set the EDITOR variable with both shells.

**Pull request closed without merging**
